Task A
DavidChibukhchian/IV-Contest-1-2 pull request #1
Opened 2024-04-13 16:44 UTC by DavidChibukhchian

Чибухчян Давид Эдуардович
Б05-232, 2 курс ФПМИ ИВТСП
ID 111276588

2024-05-22 20:47 UTC, VTroyanGolovyan requested changes

2024-05-22 20:47 UTC, VTroyanGolovyan commented on contest1taskA.cpp
> +	std::string str = pattern + SEPARATOR + text;
слишком много лишней памяти
Вместо этого сделай класс JoinStringView
JoinStringView view(pattern, sep, text)

2024-05-22 20:47 UTC, VTroyanGolovyan commented on contest1taskA.cpp
> +	std::string str = pattern + SEPARATOR + text;
(она хранит ссылки/адреса)
и имеет перегрузку [] для обращений

2024-05-22 20:47 UTC, VTroyanGolovyan commented on contest1taskA.cpp
> +	std::vector<size_t> prefix_function = calculate_prefix_function(str);
не храни всю префикс-функцию, для алгоритма КМП достаточно только префикс-функции патерна

2024-05-26 16:30 UTC, DavidChibukhchian commented on contest1taskA.cpp
> +	std::string str = pattern + SEPARATOR + text;
Я стал хранить лишь префикс-функцию паттерна, в таком случае пропала необходимость в дополнительной памяти и, как следствие, пропала нобходимость в реализации этого класса

2024-05-26 22:21 UTC, VTroyanGolovyan approved these changes

2024-05-26 23:04 UTC, merged